package com.example.tempcontacts

data class Country(val name: String, val code: String, val flagEmoji: String, val phoneLength: Int)

val countryList = listOf(
    Country("Afghanistan", "+93", "🇦🇫", 9),
    Country("Albania", "+355", "🇦🇱", 9),
    Country("Algeria", "+213", "🇩🇿", 9),
    Country("Argentina", "+54", "🇦🇷", 10),
    Country("Australia", "+61", "🇦🇺", 9),
    Country("Austria", "+43", "🇦🇹", 10),
    Country("Bangladesh", "+880", "🇧🇩", 10),
    Country("Belgium", "+32", "🇧🇪", 9),
    Country("Brazil", "+55", "🇧🇷", 11),
    Country("Canada", "+1", "🇨🇦", 10),
    Country("Chile", "+56", "🇨🇱", 9),
    Country("China", "+86", "🇨🇳", 11),
    Country("Colombia", "+57", "🇨🇴", 10),
    Country("Denmark", "+45", "🇩🇰", 8),
    Country("Egypt", "+20", "🇪🇬", 10),
    Country("Finland", "+358", "🇫🇮", 10),
    Country("France", "+33", "🇫🇷", 9),
    Country("Germany", "+49", "🇩🇪", 11),
    Country("Greece", "+30", "🇬🇷", 10),
    Country("Hong Kong", "+852", "🇭🇰", 8),
    Country("Hungary", "+36", "🇭🇺", 9),
    Country("Iceland", "+354", "🇮🇸", 7),
    Country("India", "+91", "🇮🇳", 10),
    Country("Indonesia", "+62", "🇮🇩", 10),
    Country("Iran", "+98", "🇮🇷", 10),
    Country("Iraq", "+964", "🇮🇶", 10),
    Country("Ireland", "+353", "🇮🇪", 9),
    Country("Israel", "+972", "🇮🇱", 9),
    Country("Italy", "+39", "🇮🇹", 10),
    Country("Japan", "+81", "🇯🇵", 10),
    Country("Malaysia", "+60", "🇲🇾", 9),
    Country("Mexico", "+52", "🇲🇽", 10),
    Country("Netherlands", "+31", "🇳🇱", 9),
    Country("New Zealand", "+64", "🇳🇿", 9),
    Country("Nigeria", "+234", "🇳🇬", 10),
    Country("Norway", "+47", "🇳🇴", 8),
    Country("Pakistan", "+92", "🇵🇰", 10),
    Country("Philippines", "+63", "🇵🇭", 10),
    Country("Poland", "+48", "🇵🇱", 9),
    Country("Portugal", "+351", "🇵🇹", 9),
    Country("Russia", "+7", "🇷🇺", 10),
    Country("Saudi Arabia", "+966", "🇸🇦", 9),
    Country("Singapore", "+65", "🇸🇬", 8),
    Country("South Africa", "+27", "🇿🇦", 9),
    Country("South Korea", "+82", "🇰🇷", 10),
    Country("Spain", "+34", "🇪🇸", 9),
    Country("Sweden", "+46", "🇸🇪", 9),
    Country("Switzerland", "+41", "🇨🇭", 9),
    Country("Thailand", "+66", "🇹🇭", 9),
    Country("Turkey", "+90", "🇹🇷", 10),
    Country("United Arab Emirates", "+971", "🇦🇪", 9),
    Country("United Kingdom", "+44", "🇬🇧", 10),
    Country("United States", "+1", "🇺🇸", 10),
    Country("Vietnam", "+84", "🇻🇳", 9)
)
